
# Allow directory listing on router.denjik.ru for admin paths
SecRule REQUEST_URI "@rx ^/(service|android)/" \
    "id:10020,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=950130"


# WordPress admin — load-styles.php / load-scripts.php
#SecRule REQUEST_URI "@beginsWith /wp-admin/load-" \
#    "id:10001,\
#    phase:1,\
#    pass,\
#    nolog,\
#    ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /wp-admin/" \
    "id:10010,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"

# непашет так))
# MODX manager — сохранение ресурсов с HTML/JS контентом
#SecRule REQUEST_URI "@beginsWith /connectors/" \
#    "id:10030,\
#    phase:1,\
#    pass,\
#    nolog,\
#    ctl:ruleRemoveById=932160"


# MODX ОТКРЫТЬ К ИЗМЕНЕНИЮ СТРАНИЦ!
# MODX manager — полное исключение (доступ только из локалки)
#SecRule REQUEST_URI "@beginsWith /connectors/" \
#    "id:10030,\
#    phase:1,\
#    pass,\
#    nolog,\
#    ctl:ruleEngine=Off"
